### PR TITLE
Support instantly refreshing view when view size is changed.

### PR DESCRIPTION
**Pull request by rolfrando**
This prevents a visual flash when the width or height of a view window is changed.

### CODE REVIEW

**Comment by menthays** [comment]
Thanks for your work !:smiley:

 Can you do these changes under `ts` folder since files under `js` folder were generated with script `npm run build:ts`. (And render related module were still written in javascript in temp, you just need to copy and paste these changes. Also we will optimize project structure later.)

By the way, do you think `refreshRender` sounds better than `refreshStream`. (According to exsits method: `initRender` and `destroyRender`)

**Comment by plutoless** [comment]
or `resizeRender` ?

**Comment by rolfrando** [comment]
Sorry for the delay. I'll do the ts change soon

**Comment by rolfrando** [comment]
@menthays @plutoless I updated as you requested but haven't been able to fully test because I don't have a npm repo set up. Please test it yourself before merging, or sent up a prelim branch for me to test within our app.

**Comment by menthays** [comment]
Thanks for your work. 😀

 I have do some fixed based on your previous commit and merged this pr.

BTW, we have also deleted folders like `js/, types/, docs` which will be auto-generated before publish.

**Pull request merged**
